<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:context="http://www.springframework.org/schema/context" 
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd">

    	<!-- DispatcherServlet Context: defines this servlet's request-processing 
		infrastructure -->
	<import resource="database-context.xml" />

	<context:annotation-config />
	<context:component-scan base-package="com.own.service" />
	<context:component-scan base-package="com.own.merchant.model" />
	<context:component-scan base-package="com.own.merchant.*" />
	<context:component-scan base-package="com.own.merchant" />
	<context:component-scan base-package="com.pg.spring.extension.authentication" />
	<context:component-scan base-package="com.pg.controller.service.factory" />
	<context:component-scan base-package="com.own.merchant.model.sql.generator" />
	
	<bean id="validator"
		class="org.springframework.validation.beanvalidation.LocalValidatorFactoryBean" >
		<property name="validationMessageSource" ref="messageSource" />
		<property name="providerClass" value="org.hibernate.validator.HibernateValidator" />
		<property name="validationPropertyMap">
			<map>
				<entry key="hibernate.validator.fail_fast" value="false"/>
			</map>
		</property>
		</bean>
		
		<bean id="exceptionMessageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="basenames">
			<list>
				<value>classpath:messages/error-messages</value>
			</list>
		</property>
		<property name="cacheSeconds" value="0" />
	</bean>
		
		
	<import resource="security-context.xml" />
</beans>
